package gui.internal;

import gui.iWindow;
import Validators.CharValidator;
import Validators.EmailValidator;
import Validators.PhoneValidator;
import Validators.PositiveValidator;
import core.Branch;
import core.Customer;
import core.Instrument;
import core.Lesson;
import core.Practice;
import core.Room;
import core.Subscription;
import core.Workout;
import java.awt.Color;
import utils.E_Cities;
import java.lang.*;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javafx.beans.binding.Bindings;
import javax.swing.JCheckBox;
import javax.swing.JList;
import utils.E_Lessons;
import utils.E_Rooms;
import utils.E_Types;

/**
 *
 * @author nisans
 */
public class AddInstrumentToWorkout extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form NewJInternalFrame
     */
    public AddInstrumentToWorkout() {
        initComponents();
        setTitle("Customer -> Add Intrument to Workout");
        
        //Finished Loading
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        custID = new javax.swing.JTextField();
        Connect = new javax.swing.JButton();
        custError = new javax.swing.JLabel();
        MessageBox = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        selectWorkout = new javax.swing.JComboBox<>();
        insType = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        details = new javax.swing.JLabel();
        duration = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        Hour = new javax.swing.JComboBox<>();
        Minute = new javax.swing.JComboBox<>();
        Second = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        DateError = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new Color(0,0,0,85));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        setIconifiable(true);
        setMaximizable(true);
        setAutoscrolls(true);
        setFrameIcon(null);
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 600));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        getContentPane().setLayout(null);

        custID.setBackground(new java.awt.Color(0, 0, 0));
        custID.setColumns(10);
        custID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        custID.setForeground(new java.awt.Color(255, 255, 255));
        custID.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        custID.setCaretColor(new java.awt.Color(255, 255, 255));
        custID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        custID.setSelectionColor(new java.awt.Color(204, 204, 204));
        custID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                custIDFocusLost(evt);
            }
        });
        getContentPane().add(custID);
        custID.setBounds(160, 10, 190, 21);

        Connect.setBackground(new java.awt.Color(102, 102, 102));
        Connect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Connect.setForeground(new java.awt.Color(255, 255, 255));
        Connect.setText("Add Instrument");
        Connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConnectMouseClicked(evt);
            }
        });
        getContentPane().add(Connect);
        Connect.setBounds(540, 210, 150, 23);

        custError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        custError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(custError);
        custError.setBounds(370, 10, 290, 20);

        MessageBox.setBackground(new Color (0,0,0,90));
        MessageBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MessageBox.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(MessageBox);
        MessageBox.setBounds(30, 210, 430, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Select Workout");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 40, 110, 20);

        selectWorkout.setBackground(new Color(0,0,0));
        selectWorkout.setForeground(new java.awt.Color(255, 255, 255));
        selectWorkout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Workout" }));
        selectWorkout.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                selectWorkoutFocusLost(evt);
            }
        });
        getContentPane().add(selectWorkout);
        selectWorkout.setBounds(160, 40, 190, 20);
        for(Branch b : iWindow.getDB().getBranches().values()){
            selectWorkout.addItem(b.getBranchNumber() + " " + b.getBranchName());
        }

        insType.setBackground(new java.awt.Color(0, 0, 0));
        insType.setForeground(new java.awt.Color(255, 255, 255));
        insType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Instrument Type", "CROSS", "CYCLE", "ROWER", "STEPPER", "BENCH", "KETTLEBELLS", "WEIGHTLIFTING_BAR", "POWER_STATION", "ROPE_CLIMBER", "SHOULDER_PRESS", "MATTRESS;" }));
        insType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                insTypeFocusLost(evt);
            }
        });
        getContentPane().add(insType);
        insType.setBounds(160, 70, 190, 20);
        insType.removeAllItems();

        jLabel3.setToolTipText("Subscription Number ");
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Instrument Type");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 70, 140, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Customer ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 10, 110, 20);

        details.setBackground(new Color(0,0,0,90));
        details.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(details);
        details.setBounds(370, 40, 330, 20);

        duration.setBackground(new java.awt.Color(0, 0, 0));
        duration.setForeground(new java.awt.Color(255, 255, 255));
        duration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Duration", "5 min", "10 min", "15 min", "20 min", "25 min", "30 min" }));
        duration.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                durationItemStateChanged(evt);
            }
        });
        getContentPane().add(duration);
        duration.setBounds(160, 160, 190, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Start Date");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 100, 110, 20);

        day.setBackground(new java.awt.Color(0, 0, 0));
        day.setForeground(new java.awt.Color(255, 255, 255));
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        day.setToolTipText("");
        day.setName(""); // NOI18N
        getContentPane().add(day);
        day.setBounds(160, 100, 50, 20);

        month.setBackground(new java.awt.Color(0, 0, 0));
        month.setForeground(new java.awt.Color(255, 255, 255));
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(month);
        month.setBounds(220, 100, 60, 20);

        year.setBackground(new java.awt.Color(0, 0, 0));
        year.setForeground(new java.awt.Color(255, 255, 255));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2016", "2017", "2018", "2019", "2020" }));
        year.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                yearFocusLost(evt);
            }
        });
        getContentPane().add(year);
        year.setBounds(290, 100, 60, 20);

        Hour.setBackground(new java.awt.Color(0, 0, 0));
        Hour.setForeground(new java.awt.Color(255, 255, 255));
        Hour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hour", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "18", "20", "21", "22", "23" }));
        getContentPane().add(Hour);
        Hour.setBounds(160, 130, 50, 20);

        Minute.setBackground(new java.awt.Color(0, 0, 0));
        Minute.setForeground(new java.awt.Color(255, 255, 255));
        Minute.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minute", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "18", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "34", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        getContentPane().add(Minute);
        Minute.setBounds(220, 130, 60, 20);

        Second.setBackground(new java.awt.Color(0, 0, 0));
        Second.setForeground(new java.awt.Color(255, 255, 255));
        Second.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Second", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "18", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "34", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        getContentPane().add(Second);
        Second.setBounds(290, 130, 60, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Start Time");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 130, 110, 20);

        DateError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DateError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(DateError);
        DateError.setBounds(370, 120, 250, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Duration");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 160, 110, 20);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(700, 0, 10, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectMouseClicked
        //Create the date
        if (day.getSelectedIndex() != 0 && month.getSelectedIndex() != 0
                && year.getSelectedIndex() != 0 && Hour.getSelectedIndex() !=0
                && Minute.getSelectedIndex() !=0 && Second.getSelectedIndex() !=0) {
            int d = day.getSelectedIndex();
            int m = month.getSelectedIndex()-1;
            int y =  year.getSelectedIndex()+115;
            int h = Hour.getSelectedIndex()-1;
            int min = Minute.getSelectedIndex()-1;
            int s = Second.getSelectedIndex()-1;
            
            start = new Date(y, m, d, h,min,s);
            Date workdate = iWindow.getDB().getWorkouts().get(workoutNum).getDate();
            if (new Date().before(start) && start.getYear() == workdate.getYear()
                    && start.getMonth() == workdate.getMonth() && start.getDate() == workdate.getDate()){
                DateError.setForeground(Color.GREEN);
                DateError.setText("Date: " + start);
                iWindow.update();
            }
            else{
                start = null;
                DateError.setForeground(Color.red);
                DateError.setText("Invalid date or time");
                iWindow.update();
                return;
            }
        }
        else{
            start = null;
            DateError.setForeground(Color.red);
            DateError.setText("Invalid date, time or duration");
            iWindow.update();
            return;
        }
        
        //add to ishape
        System.out.println(workoutNum + " " + branchNum + " " + roomNum + " " + start + " " + minutes);
        if (iWindow.getDB().addInstrumentToWorkout(workoutNum,branchNum, roomNum, type, start, minutes)){
            MessageBox.setForeground(Color.GREEN);
            MessageBox.setText("Instrument " + type + " was added successfully to workout " + workoutNum);
            iWindow.log(new Date().toString() + " - Instrument " + type + " was added successfully to workout " + workoutNum);
        }
        else{
            MessageBox.setForeground(Color.RED);
            MessageBox.setText("Instrument " + type + " was failed to be added to workout " + workoutNum);
            iWindow.log(new Date().toString() + " - Instrument " + type + " was failed to be added to workout " + workoutNum);
        }
        
        details.setText(iWindow.getDB().getWorkouts().get(workoutNum).toString2()); 
        iWindow.update();
        
    }//GEN-LAST:event_ConnectMouseClicked
    
    private void custIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custIDFocusLost
        String str = custID.getText();
        if (!PositiveValidator.isPositiveStringNum(str) || str.length() != 8) {
            custError.setForeground(Color.red);
            custError.setText("Positive 8 digits only");
            custNum = "-1";
            iWindow.update();
            return;
        }
        
        if (iWindow.getDB().getCustomers().containsKey(str)) {
            cust = iWindow.getDB().getCustomers().get(str);
            custError.setForeground(Color.GREEN);
            custError.setText(cust.getFirstName() +" " + cust.getLastName());
            custNum = str;
            
            selectWorkout.removeAllItems();
            for (Subscription s:cust.getSubs()){
                for (Workout w:s.getWorkouts()){
                    if (w.getDate().after(new Date())) 
                        selectWorkout.addItem(w.toString2());
                }
            }
        } else {
            custError.setForeground(Color.red);
            custError.setText("Customer ID does not exists");
            custNum = "-1";
        }
        iWindow.update();
        
        
    }//GEN-LAST:event_custIDFocusLost
    
    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusLost
        
    private void selectWorkoutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selectWorkoutFocusLost
        String str = (String) selectWorkout.getSelectedItem();
        if(str.length()<=0)
            return;
        
        for (int i = 0; i < str.length(); i++){
            if (Character.isDigit(str.charAt(i))) continue;
            else{
                str = str.substring(0, i);
            }
        }
        workoutNum = Integer.parseInt(str);
        details.setText(selectWorkout.getSelectedItem().toString());
        
        //create list of instruments for the selected workout branch
        branchNum = iWindow.getDB().getWorkouts().get(workoutNum).getBranchNum();
        Branch branch = iWindow.getDB().getBranches().get(branchNum);
        ArrayList<E_Types> list = new ArrayList<E_Types>();
        for (Room r:branch.getRooms()){
            if (!r.getRoomType().equals(E_Rooms.GYM)) continue;
            roomNum = r.getRoomNum();
            for (Instrument i:r.getInstruments()){
                if (!list.contains(i.getType()) && i.getStatus() == true) list.add(i.getType());
            }
        }
        //add the list to jbox
        insType.removeAllItems();
        for (E_Types type:list){
            insType.addItem(type.toString());
            //System.err.println(type);
        }
        
        iWindow.update();
    }//GEN-LAST:event_selectWorkoutFocusLost

    private void yearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearFocusLost

    }//GEN-LAST:event_yearFocusLost

    private void durationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_durationItemStateChanged
        minutes = duration.getSelectedIndex() * 5;
    }//GEN-LAST:event_durationItemStateChanged

    private void insTypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_insTypeFocusLost
        type = E_Types.valueOf((String)insType.getSelectedItem());
    }//GEN-LAST:event_insTypeFocusLost
                        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Connect;
    private javax.swing.JLabel DateError;
    private javax.swing.JComboBox<String> Hour;
    private javax.swing.JLabel MessageBox;
    private javax.swing.JComboBox<String> Minute;
    private javax.swing.JComboBox<String> Second;
    private javax.swing.JLabel custError;
    private javax.swing.JTextField custID;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JLabel details;
    private javax.swing.JComboBox<String> duration;
    private javax.swing.JComboBox<String> insType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JComboBox<String> selectWorkout;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
    
    //Manual variables declaration
    private String custNum = null;
    private Customer cust = null;
    private int workoutNum = -1;
    private int branchNum = -1;
    private Date start = null;
    private int roomNum = -1;
    private E_Types type = null;
    private int minutes = 0;
    
}
