package gui.internal;

import gui.iWindow;
import Validators.CharValidator;
import Validators.EmailValidator;
import Validators.PhoneValidator;
import Validators.PositiveValidator;
import core.Branch;
import core.Customer;
import core.Instrument;
import core.Lesson;
import core.Practice;
import core.Room;
import core.Subscription;
import core.Workout;
import java.awt.Color;
import utils.E_Cities;
import java.lang.*;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javafx.beans.binding.Bindings;
import javax.swing.JCheckBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import utils.E_Lessons;
import utils.E_Rooms;
import utils.E_Types;

/**
 *
 * @author nisans
 */
public class CancelWorkout extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form NewJInternalFrame
     */
    public CancelWorkout() {
        initComponents();
        setTitle("Customer -> Add Intrument to Workout");
        
        //Finished Loading
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        custID = new javax.swing.JTextField();
        Connect = new javax.swing.JButton();
        custError = new javax.swing.JLabel();
        MessageBox = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        selectWorkout = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        details = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new Color(0,0,0,85));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        setIconifiable(true);
        setMaximizable(true);
        setAutoscrolls(true);
        setFrameIcon(null);
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(600, 600));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 600));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        getContentPane().setLayout(null);

        custID.setBackground(new java.awt.Color(0, 0, 0));
        custID.setColumns(10);
        custID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        custID.setForeground(new java.awt.Color(255, 255, 255));
        custID.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        custID.setCaretColor(new java.awt.Color(255, 255, 255));
        custID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        custID.setSelectionColor(new java.awt.Color(204, 204, 204));
        custID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                custIDFocusLost(evt);
            }
        });
        getContentPane().add(custID);
        custID.setBounds(160, 10, 190, 21);

        Connect.setBackground(new java.awt.Color(102, 102, 102));
        Connect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Connect.setForeground(new java.awt.Color(255, 255, 255));
        Connect.setText("Cancel Workout");
        Connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConnectMouseClicked(evt);
            }
        });
        getContentPane().add(Connect);
        Connect.setBounds(540, 110, 150, 23);

        custError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        custError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(custError);
        custError.setBounds(370, 10, 290, 20);

        MessageBox.setBackground(new Color (0,0,0,90));
        MessageBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MessageBox.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(MessageBox);
        MessageBox.setBounds(30, 110, 430, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Select Workout");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 40, 110, 20);

        selectWorkout.setBackground(new Color(0,0,0));
        selectWorkout.setForeground(new java.awt.Color(255, 255, 255));
        selectWorkout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Workout" }));
        selectWorkout.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                selectWorkoutFocusLost(evt);
            }
        });
        getContentPane().add(selectWorkout);
        selectWorkout.setBounds(160, 40, 190, 20);
        for(Branch b : iWindow.getDB().getBranches().values()){
            selectWorkout.addItem(b.getBranchNumber() + " " + b.getBranchName());
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Customer ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 10, 110, 20);

        details.setBackground(new Color(0,0,0,90));
        details.setForeground(new java.awt.Color(51, 255, 0));
        getContentPane().add(details);
        details.setBounds(370, 40, 330, 20);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(700, 0, 10, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectMouseClicked

        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel workout? "
                + "\nNOTE: Action can't be resotred", "Remove subsription confirmation",
                JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) return;
        //remove from ishape
        if (iWindow.getDB().cancelWorkout(workoutNum)){
            MessageBox.setForeground(Color.GREEN);
            MessageBox.setText("Workout " + workoutNum + " was removed successfully from customer " + cust.getId());
            iWindow.log(new Date().toString() + " - Workout " + workoutNum + " was removed successfully from customer " + cust.getId());
        }
        else{
            MessageBox.setForeground(Color.RED);
            MessageBox.setText("Workout " + workoutNum + " was failed to be removed from customer " + cust.getId());
            iWindow.log(new Date().toString() + " - Workout " + workoutNum + " was failed to be removed from customer " + cust.getId());
        }
        
        iWindow.update();
        
    }//GEN-LAST:event_ConnectMouseClicked
    
    private void custIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custIDFocusLost
        String str = custID.getText();
        if (!PositiveValidator.isPositiveStringNum(str) || str.length() != 8) {
            custError.setForeground(Color.red);
            custError.setText("Positive 8 digits only");
            custNum = "-1";
            iWindow.update();
            return;
        }
        
        if (iWindow.getDB().getCustomers().containsKey(str)) {
            cust = iWindow.getDB().getCustomers().get(str);
            custError.setForeground(Color.GREEN);
            custError.setText(cust.getFirstName() +" " + cust.getLastName());
            custNum = str;
            
            selectWorkout.removeAllItems();
            for (Subscription s:cust.getSubs()){
                for (Workout w:s.getWorkouts()){
                    if (w.getDate().after(new Date())) 
                        selectWorkout.addItem(w.toString2());
                }
            }
        } else {
            custError.setForeground(Color.red);
            custError.setText("Customer ID does not exists");
            custNum = "-1";
        }
        iWindow.update();
        
        
    }//GEN-LAST:event_custIDFocusLost
    
    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusLost
        
    private void selectWorkoutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selectWorkoutFocusLost
        String str = (String) selectWorkout.getSelectedItem();
        if(str.length()<=0)
            return;
        
        for (int i = 0; i < str.length(); i++){
            if (Character.isDigit(str.charAt(i))) continue;
            else{
                str = str.substring(0, i);
            }
        }
        workoutNum = Integer.parseInt(str);
        details.setText(selectWorkout.getSelectedItem().toString());
        Workout w = iWindow.getDB().getWorkouts().get(workoutNum);
        if (w !=null) cust = w.getSub().getCustomer();

        iWindow.update();
    }//GEN-LAST:event_selectWorkoutFocusLost
                        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Connect;
    private javax.swing.JLabel MessageBox;
    private javax.swing.JLabel custError;
    private javax.swing.JTextField custID;
    private javax.swing.JLabel details;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> selectWorkout;
    // End of variables declaration//GEN-END:variables
    
    //Manual variables declaration
    private String custNum = null;
    private Customer cust = null;
    private int workoutNum = -1;

    
}
