/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.internal;

import core.Branch;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ItemEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;

/**
 *
 * @author nisans
 */
public class ManageCustomers extends javax.swing.JInternalFrame {
    private int WindowID = 4;
    private Object obj=null;
    /**
     * Creates new form NewJInternalFrame
     */
    public ManageCustomers() {
        initComponents();
   
        chooseCustoemr.setBackground(Color.black);
        chooseCustoemr.setForeground(Color.white);
        chooseCustoemr.removeAllItems();
        chooseCustoemr.addItem("Edit Branch");
        chooseCustoemr.setSelectedIndex(0);
        
        for(Branch branch : iWindow.DB.getBranches().values()){
            chooseCustoemr.addItem(branch.toString());
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        chooseCustoemr = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new Color(0,0,0,0));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setAutoscrolls(true);
        setFrameIcon(null);
        setInheritsPopupMenu(true);
        setMaximumSize(new java.awt.Dimension(1073, 126));
        setMinimumSize(new java.awt.Dimension(1073, 126));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1073, 126));
        getContentPane().setLayout(null);

        jLabel2.setBackground(new Color(0,0,0,0));
        jLabel2.setText("You may choose a branch by using the selector.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 510, 16);

        chooseCustoemr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        chooseCustoemr.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chooseCustoemrItemStateChanged(evt);
            }
        });
        chooseCustoemr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseCustoemrActionPerformed(evt);
            }
        });
        getContentPane().add(chooseCustoemr);
        chooseCustoemr.setBounds(20, 40, 260, 22);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 82, 1070, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseCustoemrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseCustoemrActionPerformed
  
// TODO add your handling code here:
    }//GEN-LAST:event_chooseCustoemrActionPerformed

    private void chooseCustoemrItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chooseCustoemrItemStateChanged
        // TODO add your handling code here:
         if (evt.getStateChange() == ItemEvent.SELECTED) {
          Object item = evt.getItem();
          if(item.equals("Edit Branch")) return;
          // do something with object
          String str = item.toString().substring(8, 16);
          Branch branch = new Branch(Integer.parseInt(str));
          
          AddBranchForm br = new AddBranchForm(branch);
          br.setVisible(true);
          br.setBounds(100, 100, br.getWidth(), br.getWidth());
          iWindow.getPanel().add(br);
          
          
       }
    }//GEN-LAST:event_chooseCustoemrItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chooseCustoemr;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public int getWindowID(){
        return this.WindowID;
    }

    public void setWindowID(int id){
        this.WindowID=id;
    }
}
